services:
  # -------------------------------
  # OpenTelemetry Collector
  # -------------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "55679:55679" # zPages
    depends_on:
      - jaeger
      - prometheus
      - loki

  # -------------------------------
  # Jaeger (Trace Storage + UI)
  # -------------------------------
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger Collector HTTP
      - "14250:14250" # Jaeger Collector gRPC
      - "6831:6831/udp" # Jaeger Agent UDP
      - "6832:6832/udp" # Jaeger Agent UDP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # -------------------------------
  # Prometheus (Metric Storage)
  # -------------------------------
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # -------------------------------
  # Loki (Log Storage)
  # -------------------------------
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  # -------------------------------
  # Grafana (Dashboard)
  # -------------------------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3010:3000"

  # -------------------------------
  # Postgres (Database)
  # -------------------------------
  postgres:
    image: postgres
    ports:
      - '5440:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vmxai

  # --------------------------------
  # Hashcorp Vault (Secret Storage)
  # --------------------------------
  # Only for development, use a real KMS to unseal the vault in production
  vault-kms:
    image: hashicorp/vault:latest
    ports:
      - "8201:8200"
    volumes:
      - ./docker/vault-kms/config:/vault/config
      - ./docker/vault-kms/file:/vault/file
    command: /vault/config/init.sh
    healthcheck:
      test: ["CMD", "sh", "-c", "VAULT_TOKEN=root vault read -address=http://127.0.0.1:8200 transit/keys/autounseal"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # --------------------------------
  # Hashcorp Vault (Secret Storage)
  # --------------------------------
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_NAME: vmxai
      DB_PASSWORD: password
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker/vault/config:/vault/config
    depends_on:
      postgres:
        condition: service_started
      vault-kms:
        condition: service_healthy
    command: /vault/config/init.sh

  # -------------------------------
  # Redis (Cache) Node 1
  # -------------------------------
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    ports:
      - '7001:7001'
      - '17001:17001'
    volumes:
      - ./docker/redis-config/node1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    network_mode: host

  # -------------------------------
  # Redis (Cache) Node 2
  # -------------------------------
  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    ports:
      - '7002:7002'
      - '17002:17002'
    volumes:
      - ./docker/redis-config/node2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    network_mode: host

  # -------------------------------
  # Redis (Cache) Node 3
  # -------------------------------
  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    ports:
      - '7003:7003'
      - '17003:17003'
    volumes:
      - ./docker/redis-config/node3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    network_mode: host

  # -------------------------------
  # Redis (Cache) Cluster Init
  # -------------------------------
  redis-cluster-init:
    image: redis:7
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint: >
      sh -c "
        sleep 5 &&
        echo yes | redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 --cluster-replicas 0"
    network_mode: host

  # -------------------------------
  # QuestDB (Timeseries Database)
  # -------------------------------
  timeseriesdb:
    image: questdb/questdb:9.1.1
    environment:
      QDB_PG_USER: admin
      QDB_PG_PASSWORD: password
      QDB_PG_DATABASE: vmxai
    ports:
      - '9000:9000'
      - '8812:8812'

networks:
  redisnet:
    driver: bridge
