services:
  postgres:
    image: postgres
    ports:
      - '5440:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vmxai

  # Only for development, use a real KMS to unseal the vault in production
  vault-kms:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8201:8200"
    volumes:
      - ./docker/vault-kms/config:/vault/config
    command: /vault/config/init.sh
    healthcheck:
      test: ["CMD", "sh", "-c", "VAULT_TOKEN=root vault read -address=http://127.0.0.1:8200 transit/keys/autounseal"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_NAME: vmxai
      DB_PASSWORD: password
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker/vault/config:/vault/config
    depends_on:
      postgres:
        condition: service_started
      vault-kms:
        condition: service_healthy
    command: /vault/config/init.sh

  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    ports:
      - '7001:7001'
      - '17001:17001'
    volumes:
      - ./docker/redis-config/node1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    network_mode: host

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    ports:
      - '7002:7002'
      - '17002:17002'
    volumes:
      - ./docker/redis-config/node2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    network_mode: host

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    ports:
      - '7003:7003'
      - '17003:17003'
    volumes:
      - ./docker/redis-config/node3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    network_mode: host

  redis-cluster-init:
    image: redis:7
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint: >
      sh -c "
        sleep 5 &&
        echo yes | redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 --cluster-replicas 0"
    network_mode: host

networks:
  redisnet:
    driver: bridge
