[project]
name = "nx-workspace"
version = "1.0.0"
dependencies = [ "langchain-vm-x-ai-example" ]

[tool.uv.workspace]
members = [ "examples/langchain" ]

[tool.uv.sources.langchain-vm-x-ai-example]
workspace = true

[dependency-groups]
dev = [ "autopep8>=2.3.1", "ruff>=0.8.2" ]
