{{- if and .Values.ingress.enabled (eq .Values.ingress.type "nginx") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vm-x-ai.fullname" . }}
  labels:
    {{- include "vm-x-ai.labels" . | nindent 4 }}
  {{- with .Values.ingress.nginx.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.nginx.className }}
  ingressClassName: {{ .Values.ingress.nginx.className }}
  {{- end }}
  {{- if .Values.ingress.nginx.tls }}
  tls:
    {{- range .Values.ingress.nginx.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.nginx.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if eq .service "api" }}{{ include "vm-x-ai.fullname" $ }}-api{{ else }}{{ include "vm-x-ai.fullname" $ }}-ui{{ end }}
                port:
                  number: {{ if eq .service "api" }}{{ $.Values.api.service.port }}{{ else }}{{ $.Values.ui.service.port }}{{ end }}
          {{- end }}
    {{- end }}
{{- end }}

