{{- if and .Values.vault.enabled (eq .Values.api.vault.encryptionService "hashcorp") .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vm-x-ai.fullname" . }}-vault-bootstrap
  labels:
    {{- include "vm-x-ai.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "update"]
  resourceNames:
    - {{ include "vm-x-ai.fullname" . }}-vault-approle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vm-x-ai.fullname" . }}-vault-bootstrap
  labels:
    {{- include "vm-x-ai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vm-x-ai.fullname" . }}-vault-bootstrap
subjects:
- kind: ServiceAccount
  name: {{ include "vm-x-ai.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

