{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vm-x-ai.fullname" . }}-ui
  labels:
    {{- include "vm-x-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "vm-x-ai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if not .Values.ui.istio.sidecar.enabled }}
        sidecar.istio.io/inject: "false"
        {{- else }}
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
        {{- end }}
      labels:
        {{- include "vm-x-ai.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vm-x-ai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: ui
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "vm-x-ai.image" (dict "Values" .Values "repository" .Values.images.ui.repository "tag" .Values.images.ui.tag) }}
        imagePullPolicy: {{ .Values.images.ui.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.ui.service.targetPort }}
          protocol: TCP
        env:
        - name: AUTH_URL
          value: {{ include "vm-x-ai.ui.baseUrl" . | quote }}
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "vm-x-ai.secrets.ui.name" . }}
              key: {{ include "vm-x-ai.secrets.ui.authSecretKey" . }}
        - name: AUTH_OIDC_ISSUER
          value: {{ include "vm-x-ai.oidc.issuer" . | quote }}
        - name: AUTH_OIDC_CLIENT_ID
          value: {{ .Values.ui.env.AUTH_OIDC_CLIENT_ID | quote }}
        - name: AUTH_OIDC_CLIENT_SECRET
          value: {{ .Values.ui.env.AUTH_OIDC_CLIENT_SECRET | quote }}
        - name: AUTH_REDIRECT_PROXY_URL
          value: {{ printf "%s/api/auth" (include "vm-x-ai.ui.baseUrl" .) | quote }}
        - name: API_BASE_URL
          value: {{ include "vm-x-ai.api.baseUrlWithPath" . | quote }}
        - name: NEXT_AUTH_DEBUG
          value: {{ .Values.ui.env.NEXT_AUTH_DEBUG | quote }}
        {{- if .Values.otel.enabled }}
        {{- $otelEndpoint := include "vm-x-ai.otel.exporterEndpoint" . }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ $otelEndpoint | quote }}
        - name: OTEL_LOG_LEVEL
          value: error
        {{- end }}
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
        {{- if .Values.ui.healthcheck.enabled }}
        {{- $healthcheckPath := .Values.ui.healthcheck.liveness.path }}
        {{- if .Values.ui.healthcheck.startup.enabled }}
        startupProbe:
          httpGet:
            path: {{ $healthcheckPath }}
            port: http
          initialDelaySeconds: {{ .Values.ui.healthcheck.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.ui.healthcheck.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.ui.healthcheck.startup.timeoutSeconds }}
          successThreshold: {{ .Values.ui.healthcheck.startup.successThreshold }}
          failureThreshold: {{ .Values.ui.healthcheck.startup.failureThreshold }}
        {{- end }}
        {{- if .Values.ui.healthcheck.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: {{ $healthcheckPath }}
            port: http
          initialDelaySeconds: {{ .Values.ui.healthcheck.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.ui.healthcheck.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.ui.healthcheck.liveness.timeoutSeconds }}
          successThreshold: {{ .Values.ui.healthcheck.liveness.successThreshold }}
          failureThreshold: {{ .Values.ui.healthcheck.liveness.failureThreshold }}
        {{- end }}
        {{- if .Values.ui.healthcheck.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: {{ $healthcheckPath }}
            port: http
          initialDelaySeconds: {{ .Values.ui.healthcheck.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.ui.healthcheck.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.ui.healthcheck.readiness.timeoutSeconds }}
          successThreshold: {{ .Values.ui.healthcheck.readiness.successThreshold }}
          failureThreshold: {{ .Values.ui.healthcheck.readiness.failureThreshold }}
        {{- end }}
        {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm-x-ai.fullname" . }}-ui
  labels:
    {{- include "vm-x-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vm-x-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}

