apiVersion: v2
name: vm-x-ai
description: A Helm chart for VM-X AI Application
type: application
version: 1.0.0
appVersion: '1.0.0'
keywords:
  - vm-x-ai
  - ai
  - virtual-machines
maintainers:
  - name: VM-X AI Team
